[workspace]
members = [
    # "host",
    # "my_debug",
    # "iter_help",
    # "lib",
    # "fslib",
    # "isay_hello",
    # "say_hello_console",
    "dymod",
    "engine",
    "csv_extractor",
    "sum_transform"
]
