[package]
name = "csv_extractor"
version = "0.1.0"
authors = ["Solomatov Sergei <solomatovs@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["dylib"] 

[dependencies]
models = { path = "../models", version = "*" }
rand = "0.8"
polars = "0.22.8"